name: Main CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Docs
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: documents
          path: "build/docs/example_doc.pdf"